### ISSUE TITLE
Option to accept multiple git directories 

### ISSUE THREAD

**Issue by andrecr12** [git-commit-id/git-commit-id-maven-plugin#137]
Hi, 

Firstly, I'd to congratulate you all for this great plugin. This is very useful!

Second, I'd like to ask if already exists or suggest an option to configure the plugin to read multiple Git folder information.
For instance in my current case, I have a git repo that tracks the J2EE content and another git repo that tracks just the front-end code (HTML, CSS, Js, etc):

```
- <project_root>/.git
- <project_root>/src/main/webapp/.git
```

And, it'd be great if I could track the latest version of the built package of both gits.

Maybe, setting two configuration sets with two different prefix:

```
...
<configuration>
    <prefix>git1</prefix>
    ...
</configuration>
<configuration>
    <prefix>git2</prefix>
    ...
</configuration>
```

And, instead of only one git.properties, we could have:

```
# git1.properties
git.commit.id.describe=${git1.commit.id.describe}
...
# git2.properties
git.commit.id.describe=${git2.commit.id.describe}
```

I understand that this is not very common, but I believe it'd be nice to have this plugin the most flexible as possible.

Thanks

**Comment by susannamichael54** [comment]
Hi, I was trying to generate the properties file for a submodule along with the parent module. I am using version 4.0.0 of the plugin. The solution of using two executions, as shown above, does not work in my case because the configuration tag is not valid within the execution tag for the version. Could you suggest an alternative?

**Comment by TheSnoozer** [comment]
Hello, what do you mean by `configuration tag is not valid within the execution tag for the version` -  i don't understand :-)

As a side note: please create a new issue for your problem.

**Comment by susannamichael54** [comment]
Hi, I am really sorry about that. I got something wrong. Sorry for the inconvenience.
