### ISSUE TITLE
Maven 3: Plugin execution not covered by lifecycle configuration

### ISSUE THREAD

**Issue by Raptor399** [git-commit-id/git-commit-id-maven-plugin#22]
Hi,

Thanks for this great plugin!
I am using it with Maven 3, configured as follows:

```
        <plugin>
            <groupId>pl.project13.maven</groupId>
            <artifactId>git-commit-id-plugin</artifactId>
            <version>1.9</version>
            <executions>
                <execution>
                    <phase>initialize</phase>
                    <goals>
                        <goal>revision</goal>
                    </goals>
                </execution>
            </executions>
            <configuration>
                <dateFormat>yyyy-MM-dd</dateFormat>
                <verbose>false</verbose>
                <generateGitPropertiesFile>false</generateGitPropertiesFile>
            </configuration>
        </plugin>
```

However, Eclipse does not like it and reports an error at the `<execution>` line:

> Plugin execution not covered by lifecycle configuration: pl.project13.maven:git-commit-id-plugin:1.9:revision (execution: default, phase: initialize)

On Mac OS X it works regardless, but on Windows the error results in a build failure.

I have experimented a bit to see if other phases would work. It turns out that of the [default Maven lifecycle](http://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Lifecycle_Reference) only the following are accepted by Eclipse:
- test
- package
- verify
- install
- deploy

Sadly, all of these phases are too late to make use of the properties.

Is there a way to get Maven 3 to run the plugin before the process-resources phase ("initialize" would be ideal)?

**Comment by TheSnoozer** [comment]
fixed by https://github.com/ktoso/maven-git-commit-id-plugin/pull/55
