### ISSUE TITLE
No able to use the branch name or any property inside the maven artifact name

### ISSUE THREAD

**Issue by hhamaky** [git-commit-id/git-commit-id-maven-plugin#461]
Description:
I am not able to use the plugin, not sure if it is a bug or not. I want to identify my feature branches with the feature branch name, just concatenate the branch name to the snapshot version to be like that     <version>1.0.5-${git.branch}-SNAPSHOT</version>

To get the GIT branch name , I am using the plugin as below.
My project consists of parent maven module and 5 submodules.

The generated git.properties file is include only in the target of the submodules, not the parent module and it is in JSON format , I don't know if that cause issue or not.
The generated snapshot looks like that "1.0.5-${git.branch}-SNAPSHOT" - > ${git.branch} is not replaced with the branch name

```xml
<plugin>                                                                                                                                   
    <groupId>pl.project13.maven</groupId>                                                                                                  
    <artifactId>git-commit-id-plugin</artifactId>                                                                                          
    <version>4.0.0</version>                                                                                                               
    <executions>                                                                                                                           
        <execution>                                                                                                                        
            <goals>                                                                                                                        
                <goal>revision</goal>                                                                                                      
            </goals>                                                                                                                       
        </execution>                                                                                                                       
    </executions>                                                                                                                          
    <configuration>                                                                                                                        
        <prefix>git</prefix>                                                                                                               
        <verbose>true</verbose>                                                                                                            
        <dotGitDirectory>${project.basedir}/.git</dotGitDirectory>                                                                         
        <injectAllReactorProjects>true</injectAllReactorProjects>                                                                          
        <injectIntoSysProperties>true</injectIntoSysProperties>                                                                            
        <generateGitPropertiesFile>true</generateGitPropertiesFile>                                                                        
        <useBranchNameFromBuildEnvironment>true</useBranchNameFromBuildEnvironment>                                                        
        <generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties</generateGitPropertiesFilename>                     
    </configuration>                                                                                                                       
</plugin>                                                                                                                                  
```
I used maven ant plugin to debug the issue and the echo works 
                                <echo>Extracted git-Branch: ${git.branch}</echo>    
Result:
 [echo] Extracted git-Branch: feature/GROUP-49658-2

so the problem is actually in putting the value in the maven version of the parent and child poms

**Comment by TheSnoozer** [comment]
Hello,
thank you for reporting your issue here.
Based on your description you might need to set `<skipPoms>false</skipPoms>`

I also want to outline that the support of dynamic versions in maven is somewhat not officially supported.

When setting a dynamic version one gets an error like:
```
[ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'version' contains an expression but should be a constant. @ pl.project13.maven:git-commit-id-plugin-debugging:0.0.3-${git.branch}-SNAPSHOT
```
so as of now one can only use the ```<build><finalName>.....</finalName></build>```.

Unfortunately this does not work for `install` or `deploy` - you might want to check if the workaround in the FAQ still works:
https://github.com/git-commit-id/maven-git-commit-id-plugin/blob/master/maven/docs/faq.md#generated-properties-are-not-being-used-in-install-andor-deploy

Perhaps you can give the `flatten-maven-plugin` a try if you really want to have such naming for your artifacts.

**Comment by TheSnoozer** [comment]
Could you get this to work?

**Comment by TheSnoozer** [comment]
Closing since I pointed to various workarounds and underlying reasons why this is not possible with maven...hence I would claim it is working as expected....
