### ISSUE TITLE
'dependencies.dependency.version' for com.org-id.service:project-module-b:jar must be a valid version but is '${git.commit.time}.${git.commit.id.abbrev}'

### ISSUE THREAD

**Issue by AOladipupo** [git-commit-id/git-commit-id-maven-plugin#468]
### Describe the bug
I have a multi-module maven project with the structure below
-- DirectoryName
  |- project-module-a
  |- project-module-b
  |- project-module-c
  |- project-module-d
  |- pom.xml

The submodules inherit version numbers from the aggregate pom. In addition, project-module-c specifies a dependency on project-module-b in its pom.xml as shown below:

                  <dependency>
			<groupId>${project.parent.groupId}</groupId>
			<artifactId>project-module-b</artifactId>
			<version>${project.version}</version>
		</dependency>

Whenever I initiate a maven build on the project, it fails with the error: 'dependencies.dependency.version' for com.org-id.service:project-module-b:jar must be a valid version but is '${git.commit.time}.${git.commit.id.abbrev}'
### Steps to Reproduce
- Please include the **full** configuration of the plugin

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<groupId>com.org-id.service</groupId>
	<artifactId>project.service</artifactId>
	<version>${versionNumber}</version>
	<packaging>pom</packaging>
	<modelVersion>4.0.0</modelVersion>

	<name>Project Service :: Aggregate POM</name>
	<description>Project Service :: Aggregate POM</description>

	<modules>
		<module>project-module-a</module>
		<module>project-module-b</module>
		<module>project-module-c</module>
		<module>project-module-d</module>
	</modules>

	<properties>
		<!-- <versionNumber>0.0.1-SNAPSHOT</versionNumber> -->
		<versionNumber>${git.commit.time}.${git.commit.id.abbrev}</versionNumber>
		<fuse.version>7.4.0.fuse-740036-redhat-00002</fuse.version>
		<mapstructVersion>1.2.0.Final</mapstructVersion>

		<!-- Code Quality -->
		<junitVersion>5.4.2</junitVersion>

		<!-- Maven Plugins Version -->
		<mavenSurefirePluginVersion>2.22.2</mavenSurefirePluginVersion>
		<mavenFailsafePluginVersion>2.22.2</mavenFailsafePluginVersion>
		<project13GitCommitIdPluginVersion>2.2.5</project13GitCommitIdPluginVersion>
		<codehausFlattenMavenPlugin>1.0.0</codehausFlattenMavenPlugin>
		<codehausMavenBuildHelperPluginVersion>3.0.0</codehausMavenBuildHelperPluginVersion>

	</properties>

	<build><plugins>
   <plugin>
				<groupId>pl.project13.maven</groupId>
				<artifactId>git-commit-id-plugin</artifactId>
				<version>${project13GitCommitIdPluginVersion}</version>
				<executions>
					<execution>
						<id>get-the-git-infos</id>
						<goals>
							<goal>revision</goal>
						</goals>
						<phase>initialize</phase>
					</execution>
					<execution>
						<id>validate-the-git-infos</id>
						<goals>
							<goal>validateRevision</goal>
						</goals>
						<phase>package</phase>
					</execution>
					<!-- <execution> -->
					<!-- <phase>validate</phase> -->
					<!-- <goals> -->
					<!-- <goal>revision</goal> -->
					<!-- </goals> -->
					<!-- </execution> -->
				</executions>
				<configuration>
					<dateFormat>yyyyMMdd-HHmmss</dateFormat>
					<dotGitDirectory>${project.basedir}/.git</dotGitDirectory>
					<generateGitPropertiesFile>false</generateGitPropertiesFile>
					<injectAllReactorProjects>true</injectAllReactorProjects>
					<runOnlyOnce>true</runOnlyOnce>
					<verbose>true</verbose>
					<skipPoms>false</skipPoms>
				</configuration>
			</plugin>
...
</plugins>
```

### Expected behavior
- I want maven to be able to access the git info while calculating dependency versions. This would make it possible to expand the variable ${git.commit.time}.${git.commit.id.abbrev} before the plugins get fired.

**Comment by TheSnoozer** [comment]
Hello,
thank you for reporting your issue here.
Unfortunately I might be able to provide any support or help for your request. In short Maven is not designed for dynamic versions and whenever you try to specify a dynamic version you'll get `'version' contains an expression but should be a constant.`. This is certainly not a limitation of this plugin, but of maven in general.
You might be able to get away with the https://www.mojohaus.org/flatten-maven-plugin/usage.html.

See also:
https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/409#issuecomment-460344888
https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/377#issuecomment-413723156
