### ISSUE TITLE
Move contributing section from faq.md to CONTRIBUTING.md

### ISSUE THREAD

**Issue by Marcono1234** [git-commit-id/git-commit-id-maven-plugin#482]
What do you think about moving the ["How to contribute to the project"](https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/master/maven/docs/faq.md#how-to-contribute-to-the-project) section of the `faq.md` to a [`CONTRIBUTING.md`](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors#adding-a-contributing-file) file so GitHub can show the information to new contributors?

Additionally it might be good to describe the project layout in `CONTRIBUTING.md` then, so new contributors know that this is a multi-module Maven project and understand the meaning of the `core` and `maven` modules.

**Comment by TheSnoozer** [comment]
Hello, thank you for raising this improvement! 
Sure feel free to add it to https://github.com/git-commit-id/git-commit-id-maven-plugin/pull/481 :-)

**Comment by Marcono1234** [comment]
Done, could you please have a look at it and let me know if you would like something to be changed? Or just change it yourself, if you want to.

**Comment by Marcono1234** [comment]
Closing issue because this has been fixed with #481
