### ISSUE TITLE
Improve BigDiffTest

### ISSUE THREAD

**Issue by Marcono1234** [git-commit-id/git-commit-id-maven-plugin#483]
BigDiffTest takes compared to all other tests a rather long time, for me it needs about 4 minutes.
Apparently most of that time comes from writing 100000 (**!**) files. Could you please check if there are other ways to implement this test?

Long build / testing times make it less attractive for people to run the tests, which could decrease code quality. Additionally writing that many files puts in my opinion an unjustified amount of work on the file system.

**Comment by TheSnoozer** [comment]
Please make a PR with concrete suggestions.

**Comment by Marcono1234** [comment]
@TheSnoozer, my suggestion would be to remove / disable the test (or if really necessary, at least only run it on CI). I know this is not a great solution, but in my opinion creating 100.000 files is out of proportion to what this test is covering.

Take a look for example at the recent GitHub "Run basic test with Java" workflow runs: The "Build with Maven" step takes ~1 minute, and of that `BigDiffTest` takes ~35 seconds. That is more than 50% of the complete Maven build taken just by that one test.

But in the end it is of course your decision. If you think this is justified, then just keep it as it is.
