### ISSUE TITLE
Clarify "Plugin compatibility with Maven" in README

### ISSUE THREAD

**Issue by Marcono1234** [git-commit-id/git-commit-id-maven-plugin#484]
The Maven compatibility matrix in the README is slightly confusing because it has the following entry for "Maven 3.0":
> | Maven Version               | Plugin Version  | Notes                                                                           |
> | --------------------------- | ---------------:|:-------------------------------------------------------------------------------:|
> Maven 3.0   (and onwards) | from 2.2.4 | With Maven 3.0.X SLF4J fails to load class "org.slf4j.impl.StaticLoggerBinder".

If this only applies to 3.0.X, then the "onwards" should probably be removed. And it would be good if that was in the first row of the table.
Additionally what is the "from 2.2.4" supposed to mean given that for the other versions, it says "any"?

**Comment by TheSnoozer** [comment]
Hello,
thanks for creating this.
I have tried to clarify the situation by separating the `3.0.X` version. Should be solved once https://github.com/git-commit-id/git-commit-id-maven-plugin/pull/487 is merged.

**Comment by Marcono1234** [comment]
Thanks, but to be honest I still think it is pretty confusing, though maybe I am not understanding Maven version numbering, Maven backported the changes, or this plugin was changed to support specific Maven versions?

1. It says: "Maven 3.1.0 (and below): up to 2.1.13", but at the same time "Maven 3.0 (and onwards): from 2.2.4". Isn't that a contradiction since I would expect Maven 3.1.0 > Maven 3.0, therefore the statement about "Maven 3.0" should apply as well?

2. The Maven version ordering is confusing: "3.1, 3.0, 3.3", why not "3.0, 3.1, 3.3"?

**Comment by TheSnoozer** [comment]
Mhh I hope https://github.com/git-commit-id/git-commit-id-maven-plugin/pull/488 now shines more light on what is supported. Please let me know if something still needs more clarification.

**Comment by Marcono1234** [comment]
Thank you for the extra amount of work you have put into this! It is in my opinion more clear now.
