### ISSUE TITLE
Travis and Coveralls badges / shields on README are broken

### ISSUE THREAD

**Issue by Marcono1234** [git-commit-id/git-commit-id-maven-plugin#485]
### Describe the bug
The Travis and Coveralls badges / shields in the README link to non-existent projects.
If Travis is not used anymore, it would be good if the badge was removed.

It appears Coveralls is still used in the GitHub workflow, in this case could you please check what the correct link is?

**Comment by TheSnoozer** [comment]
Hello,
thank you for creating this issue!
This is related to https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/465 where the project was renamed from 'maven-git-commit-id-plugin' to 'git-commit-id-maven-plugin' to avoid any conflicts with any license stuff.
Should be fixed once https://github.com/git-commit-id/git-commit-id-maven-plugin/pull/487 is merged.

**Comment by Marcono1234** [comment]
Thanks, closing this as the issue has been fixed.
