### ISSUE TITLE
Add a quiet mode

### ISSUE THREAD

**Issue by jdeolive** [git-commit-id/git-commit-id-maven-plugin#49]
This plugin is great! So great I want to avoid it having output anything because it just works :) We have a project in which there are many modules built. The git commit id log takes up much of the maven output. For example see http://hudson.opengeo.org/hudson/job/geotools-master/4575/console

So I would like to be able to set an option to prevent most or all of the output. What do you think about a new option named "quiet" that when set would prevent the regular output. Keeping it by default unset of course. 

Happy to submit a pull request for this one but just wanted to run the idea by first. 

Thanks for the great plugin! It's indispensable for the projects we work on.

**Comment by TheSnoozer** [comment]
Updated docs with https://github.com/ktoso/maven-git-commit-id-plugin/commit/3c960e553c7319c5a7d4f409e576126276f7b8ad
