### ISSUE TITLE
Using git-commit-id-plugin on OpenShift

### ISSUE THREAD

**Issue by giovannilt** [git-commit-id/git-commit-id-maven-plugin#50]
is possible integrate pl.project13.maven with openshift deployment!?

**Comment by tavolate** [comment]
I still have this problem. I modified my configuration with the giovannilt suggestion but I have this issue:

org.eclipse.jgit.errors.NoWorkTreeException: Bare Repository has neither a working tree, nor an index
remote: 	at org.eclipse.jgit.lib.Repository.getWorkTree(Repository.java:1246)
remote: 	at org.eclipse.jgit.treewalk.FileTreeIterator.<init>(FileTreeIterator.java:88)
remote: 	at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:126)
remote: 	at pl.project13.jgit.DescribeCommand.findDirtyState(DescribeCommand.java:362)
remote: 	at pl.project13.jgit.DescribeCommand.call(DescribeCommand.java:298)
remote: 	at pl.project13.maven.git.JGitProvider.getGitDescribe(JGitProvider.java:222)
remote: 	at pl.project13.maven.git.JGitProvider.getGitDescribe(JGitProvider.java:107)
remote: 	at pl.project13.maven.git.GitDataProvider.maybePutGitDescribe(GitDataProvider.java:120)
remote: 	at pl.project13.maven.git.GitDataProvider.loadGitData(GitDataProvider.java:88)
remote: 	at pl.project13.maven.git.GitCommitIdMojo.loadGitDataWithJGit(GitCommitIdMojo.java:527)
remote: 	at pl.project13.maven.git.GitCommitIdMojo.loadGitData(GitCommitIdMojo.java:500)
remote: 	at pl.project13.maven.git.GitCommitIdMojo.execute(GitCommitIdMojo.java:356)
remote: 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
remote: 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
remote: 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
remote: 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
remote: 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
remote: 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
remote: 	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
remote: 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
remote: 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
remote: 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
remote: 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
remote: 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
remote: 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
remote: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
remote: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
remote: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
remote: 	at java.lang.reflect.Method.invoke(Method.java:606)
remote: 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
remote: 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
remote: 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
remote: 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)

**Comment by TheSnoozer** [comment]
Hi @tavolate,
thanks for reporting your issue.
Could you open a sepearte issue for your problem?
Also to help you as quickly as possible can you clarify under which conditions the build fails?
Where does it get's executed (local/CI)?
What Java / mvn-version?
How does you config currently look like?
Anything can help here.

Thanks,
