### ISSUE TITLE
I was wondering if I can ask how to make it work

### ISSUE THREAD

**Issue by MarErm27** [git-commit-id/git-commit-id-maven-plugin#504]
### Description
Please provide a brief summary of the issue and provide a summarised description in the title above.
I follow this [instruction ](https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/master/maven/docs/using-the-plugin.md)
So I add a plugin
```
  <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <defaultGoal>install</defaultGoal>
        <plugins>
            <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <version>4.0.0</version>
                <executions>
                    <execution>
                        <id>get-the-git-infos</id>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                        <phase>initialize</phase>
                    </execution>
                </executions>
                <configuration>
                    <generateGitPropertiesFile>true</generateGitPropertiesFile>
                    <generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties</generateGitPropertiesFilename>
                    <includeOnlyProperties>
                        <includeOnlyProperty>^git.build.(time|version)$</includeOnlyProperty>
                        <includeOnlyProperty>^git.commit.id.(abbrev|full)$</includeOnlyProperty>
                    </includeOnlyProperties>
                    <commitIdGenerationMode>full</commitIdGenerationMode>
                </configuration>
            </plugin>
            ...
```
added a file with name application.properies that contains only one row
```
app.build.git.branch=${git.branch}
```
and then I'm trying to get the properties this way
```
        String filename = null;
        Properties property = new Properties();

        try {
            filename = "/application.properties";
            InputStreamReader input = new InputStreamReader(getClass().getResourceAsStream(filename));
            property.load(input);
            String branchName = property.getProperty("app.build.git.branch");
            log.info(
                    "git branch: "+ branchName +",\n"
            );
        } catch (IOException e) {
            log.error("file not found: " + filename);
        }
```

### Expected behavior
- Please provide a description of what you expected to happen.

After I build the project I go to target\classes\application.properties and it contains
```
app.build.git.branch=${git.branch}
```
but I expected to find there
```
app.build.git.branch="nameOfABranch"
```
What am I missing?
### Additional context
For reproducibility please provide the following:

- the plugin version is being used (if not included in the configuration)
```
 <version>4.0.0</version>
```
- the Java-Version is being used (output of ``java -version`` and also include details about oracle-jdk VS open-jdk) 
```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```
- the Maven-Version is being used (output of ``mvn --version``)
build in Idea Intellij Community edition
- on what Operating System you experience the bug (on Linux run ``lsb_release -a`` or ``cat /etc/*release*``)
```
Windows 64 bit
```
- in what context maven is being executed (e.g. inside Windows Terminal, Powershell, Git Bash, /bin/bash, ...)
```
IDE
```
- how maven is being executed (e.g. ``mvn clean deploy`` VS ``mvn deploy:deploy``)
```
clean compile package axis2-aar:aar
```
Feel free to add any other context or screenshots about the bug.

**Comment by TheSnoozer** [comment]
Hi thank you for creating this issue here and sorry for the delay (quite busy).

In general the filtering you are asking for is [Maven's Resource Filtering](https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html).

When I place a `application.properties` in `src/main/resources` that contains the following line:

```
app.build.git.branch=${git.branch}
```

And my pom.xml has the following config:
```
<plugin>
	<groupId>pl.project13.maven</groupId>
	<artifactId>git-commit-id-plugin</artifactId>
	<version>4.0.0</version>
	<executions>
		<execution>
			<id>get-the-git-infos</id>
			<goals>
				<goal>revision</goal>
			</goals>
			<phase>initialize</phase>
		</execution>
	</executions>
</plugin>
```
and I run ```mvn clean package``` the resulting file in `target/classes/application.properties` contains the resolved properties.


I might just want to point out:
If you want to use your own filtering, why ask the plugin to generate a properties-file (e.g. `generateGitPropertiesFile` and `generateGitPropertiesFilename` could be thrown away)
If you want to use the `git.branch` in the generated properties pay a close eye on what properties you exclude/include. For security reasons the plugin can be told to not generate certain properties to avoid an accidental leakage. Your `<includeOnlyProperties>` block ensures that only the properties matching `^git.build.(time|version)$` and `^git.commit.id.(abbrev|full)$` are generated. A `git.branch` is not generated and thus can not be resolved.

Hope this helps.

**Comment by MarErm27** [comment]
> 
> 
> Hi thank you for creating this issue here and sorry for the delay (quite busy).
> 
> In general the filtering you are asking for is [Maven's Resource Filtering](https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html).
> 
> When I place a `application.properties` in `src/main/resources` that contains the following line:
> 
> ```
> app.build.git.branch=${git.branch}
> ```
> 
> And my pom.xml has the following config:
> 
> ```
> <plugin>
> 	<groupId>pl.project13.maven</groupId>
> 	<artifactId>git-commit-id-plugin</artifactId>
> 	<version>4.0.0</version>
> 	<executions>
> 		<execution>
> 			<id>get-the-git-infos</id>
> 			<goals>
> 				<goal>revision</goal>
> 			</goals>
> 			<phase>initialize</phase>
> 		</execution>
> 	</executions>
> </plugin>
> ```
> 
> and I run `mvn clean package` the resulting file in `target/classes/application.properties` contains the resolved properties.
> 
> I might just want to point out:
> If you want to use your own filtering, why ask the plugin to generate a properties-file (e.g. `generateGitPropertiesFile` and `generateGitPropertiesFilename` could be thrown away)
> If you want to use the `git.branch` in the generated properties pay a close eye on what properties you exclude/include. For security reasons the plugin can be told to not generate certain properties to avoid an accidental leakage. Your `<includeOnlyProperties>` block ensures that only the properties matching `^git.build.(time|version)$` and `^git.commit.id.(abbrev|full)$` are generated. A `git.branch` is not generated and thus can not be resolved.
> 
> Hope this helps.

Hello!
I'm trying to add an invoice to QuickBooks by web connector, but it can't find an item and because of that can't create an invoice. How to create an item if it's not found in a separate transaction
I guess I need to use this https://developer.intuit.com/app/developer/qbdesktop/docs/api-reference/qbdesktop/iteminventoryadd
but I can't find an example how to do it

here is an example how to add a Customer

public String addCustomer() throws QBDB.DbException, JAXBException, URISyntaxException, IOException, ClassNotFoundException {
  Input input = getInput();
  List<Invoice> invoices = input.getInvoices();
  String xml = "";
  QBXML qbXML = new QBXML();
  QBXMLMsgsRq xmlMsgRq = new QBXMLMsgsRq();
  xmlMsgRq.setOnError("continueOnError");
  qbXML.setQBXMLMsgsRq(xmlMsgRq);  List<Object> reqList = xmlMsgRq.getHostQueryRqOrCompanyQueryRqOrCompanyActivityQueryRq();
  int i = 1;  for (Invoice invoice : invoices) {    CustomerRef ref = getCustomerRefForEmail(invoice.getEmail());
    String idChk = ref.getListID();
    if (idChk.equals("-1")) {
      CustomerAddRqType customerAddRq = new CustomerAddRqType();
      reqList.add(customerAddRq);
      customerAddRq.setRequestID(i++ + "");
      CustomerAdd cust = new CustomerAdd();
      customerAddRq.setCustomerAdd(cust);
      //   cust.setEmail(invoice.getEmail());//email);
      cust.setName("watchmaxx");
      cust.setFirstName(invoice.getEmail());
      cust.setCompanyName("watchmaxx");
    }
  }
  xml = getRequestXml(qbXML);
  return xml;
}

Please, help, how to add an item so QuickBooks can make an item reference

**Comment by TheSnoozer** [comment]
Seems like you sent this by accident. Since this is not related to the plugin I'm going ahead and close this issue. Feel free to reopen if you still can't get the initial problem (related to this plugin) to work. For any other questions use stackoverflow or other resources.
