### ISSUE TITLE
git rev-parse --short HEAD vs git.commit.id.abbrev

### ISSUE THREAD

**Issue by leonroy** [git-commit-id/git-commit-id-maven-plugin#505]
When running `git rev-parse --short HEAD` I get a hash with length 8 like: `ae5d88b3`

However `git.commit.id.abbrev` returns a hash with length 7.

Any reason for the disparity?

**Comment by TheSnoozer** [comment]
Hello,
thank you for creating this issue and pointing out this discrepancy.
In short in older versions of git the abbrev was defaulting to 7.
See for example the https://git-scm.com/docs/git-rev-parse/2.12.5:
```
--short
--short=number

    Instead of outputting the full SHA-1 values of object names try to abbreviate them to a shorter unique name. When no length is specified 7 is used. The minimum length is 4.
```
When looking at the current docs (https://git-scm.com/docs/git-rev-parse and https://git-scm.com/docs/git-config) one can observe that git tries to be smart and will now try to ensure that the abbrev is a unique prefix:
```
core.abbrev

    Set the length object names are abbreviated to. If unspecified or set to "auto", an appropriate value is computed based on the approximate number of packed objects in your repository, which hopefully is enough for abbreviated object names to stay unique for some time. The minimum length is 4.
```
That means that you will get different results on different repositories (e.g. clone the linux repo and the length will default to 10 or 11 depending on what is collision free).

From the perspective of the plugin one can [configure the abbrev](https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/65250ba95abd3c0a67315a7fab94a1c0b7ccc077/maven/src/main/java/pl/project13/maven/git/GitCommitIdMojo.java#L155) which defaults to 7.

To be fair I see that this is a clear inconsistency but I'm somewhat hesitant to introduce extra logic that tries to find out the "right" short size. The parameter can be configured by the user e.g. by specifying `<abbrevLength>7</abbrevLength>`. That for me sounds sufficient.

See also https://stackoverflow.com/a/21015031 for more details.
