### ISSUE TITLE
git checkout commitid, how to get git branch??like master develop etc.

### ISSUE THREAD

**Issue by xu-xiwei** [git-commit-id/git-commit-id-maven-plugin#508]
### Describe your idea
Please provide a brief summary of your idea and provide a summarised description in the title above.

### Expected Behavior
If you're suggesting a change/improvement, tell us a bit more about the problem you attempt to solve and how you idea helps to solve it.
Include a brief description of what you think should happen, maybe even how it should work and how you plan on using it.
Ex. I'm always frustrated when [...]

### Additional context
Add any other context or screenshots about the feature request.

**Comment by TheSnoozer** [comment]
Please checkout the FAQ:
https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/master/maven/docs/using-the-plugin.md#generated-properties

With the default config the branch should be available via `${git.branch}`.

**Comment by TheSnoozer** [comment]
Closing as answered. Feel free to reopen if something is still unclear.
