### ISSUE TITLE
Allow initial git.build.time from project.build.outputTimestamp to support reproducible builds

### ISSUE THREAD

**Issue by kylixs** [git-commit-id/git-commit-id-maven-plugin#509]
### Describe your idea
following Maven's guide https://maven.apache.org/guides/mini/guide-reproducible-builds.html
After add a `project.build.outputTimestamp` property to the project's `pom.xml` with the timestamp value, the output should be reproducible.

But there is no way to use `project.build.outputTimestamp` as the initial value of `git.build.time`,
it is always initialized to the current time of the system:

```
  // git-commit-id-plugin-core : pl.project13.core.cibuild.BuildServerDataProvider
  private void loadBuildVersionAndTimeData(@Nonnull Properties properties) {
    Supplier<String> buildTimeSupplier = () -> {
      Date buildDate = new Date();
      SimpleDateFormat smf = new SimpleDateFormat(dateFormat);
      if (dateFormatTimeZone != null) {
        smf.setTimeZone(TimeZone.getTimeZone(dateFormatTimeZone));
      }
      return smf.format(buildDate);
    };
    maybePut(properties, GitCommitPropertyConstant.BUILD_TIME, buildTimeSupplier);

```

**Comment by TheSnoozer** [comment]
Thanks for creating an issue here. Good point. Sounds like the plugin should respect that property (if available)
