### ISSUE TITLE
Failed to execute goal pl.project13.maven:git-commit-id-plugin:4.0.2:revision (default) on project presto-spi: Could not complete Mojo execution... Task java.util.concurrent.CompletableFuture$AsyncSupply

### ISSUE THREAD

**Issue by wendigo** [git-commit-id/git-commit-id-maven-plugin#524]
PrestoSQL updated it's git-commit-id-plugin dependency to 4.0.2 which is broken and affected by JGit dependency update that includes the following bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=564202:

```
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:4.0.2:revision (default) on project presto-spi: Could not complete Mojo execution... Task java.util.concurrent.CompletableFuture$AsyncSupply@78e305f1 rejected from java.util.concurrent.ThreadPoolExecutor@67cff96d[Running, pool size = 5, active threads = 5, queued tasks = 0, completed tasks = 0] -> [Help 1]
```

Solution: JGit dependency needs to be updated.

**Comment by TheSnoozer** [comment]
Thanks again for creating a ticket with the relevant MR that fixes the issue! Should be fixed via https://github.com/git-commit-id/git-commit-id-maven-plugin/pull/525
