### ISSUE TITLE
log execution actions

### ISSUE THREAD

**Issue by delanym** [git-commit-id/git-commit-id-maven-plugin#536]
Most plugins describe what they are doing in the execution. For example, maven-enforcer-plugin will output something like

    [main] [INFO] Adding ignore: module-info                                                               
    [main] [INFO] Adding ignore: META-INF/versions/*/module-info

Please include the same. For example, if **runOnlyOnce** is true, then I would expect to see executions from the child projects output

    [main] [INFO] Skipping...

**Comment by TheSnoozer** [comment]
Hi,
thanks for creating this issue. Have you tried setting the configuration `<verbose>true</verbose>`. IMHO that should do exactly what you ask for :-)

**Comment by delanym** [comment]
Thanks
