### ISSUE TITLE
Append unique id when dirty

### ISSUE THREAD

**Issue by almson** [git-commit-id/git-commit-id-maven-plugin#541]
My use case for this plugin is to tag docker images. I want my repository to be configured to be immutable, and I would like to be able to push `-dirty` images multiple times. In order for that to work, the tags need to be distinct by way of an additional id. It can be a build number, sha of the working tree, or random digits. This id should only be appended if the working tree is not identical to the HEAD.

**Comment by almson** [comment]
I achieved what I wanted by setting the `dirty` property using the built-in `maven.build.timestamp`:

            <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
               ...
                <configuration>
                    <gitDescribe>
                        <dirty>-dirty-${maven.build.timestamp}</dirty>
                    </gitDescribe>
                </configuration>
            </plugin>

**Comment by TheSnoozer** [comment]
Cool. Glad you could solve this on our own. Since I think you found the solution already I'm going ahead and close this. Please feel free to reopen if you need further assistance.
