### ISSUE TITLE
Optimizing actuator/info output

### ISSUE THREAD

**Issue by ravishmahur** [git-commit-id/git-commit-id-maven-plugin#555]
### Describe your idea
if using includeOnlyProperty we have selected only one field under git.commit.id which is full then in actuator/info endpoint why cant we display only commit.id instead of commit.id.full

### Expected Behavior
display only commit.id instead of commit.id.full and instead of commit.message.full why cant we have commit.message when we have included only full messsage

<img width="930" alt="Screenshot 2021-06-07 at 1 58 06 AM" src="https://user-images.githubusercontent.com/18235795/120939331-3ddcb280-c735-11eb-9dfb-8ba0a460ea70.png">

**Comment by TheSnoozer** [comment]
What is the problem with the plugin? I'm not understanding your problem.
Please provide a full configuration. There is a reason why creating an issue asks so many questions.

**Comment by TheSnoozer** [comment]
I'm going ahead and close this. Please specify what you need exactly, or what is not working otherwise I can't help.
