### ISSUE TITLE
 io.github.git-commit-id:git-commit-id-maven-plugin:jar:4.0.0 is not available in Maven Central

### ISSUE THREAD

**Issue by zosrothko** [git-commit-id/git-commit-id-maven-plugin#572]
### Describe the bug
[ERROR] Plugin io.github.git-commit-id:git-commit-id-maven-plugin:4.0.0 or one of its dependencies could not be resolved: Could not find artifact io.github.git-commit-id:git-commit-id-maven-plugin:jar:4.0.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

### Steps to Reproduce
- Please include the **full** configuration of the plugin

```xml
				<groupId>io.github.git-commit-id</groupId>
				<artifactId>git-commit-id-maven-plugin</artifactId>
				<version>${git-commit-id-maven-plugin.version}</version>
				<executions>
					<execution>
						<id>get-the-git-infos</id>
						<goals>
							<goal>revision</goal>
						</goals>
						<phase>initialize</phase>
					</execution>
				</executions>
				<configuration>
					<generateGitPropertiesFile>true</generateGitPropertiesFile>
					<generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties</generateGitPropertiesFilename>
					<includeOnlyProperties>
						<includeOnlyProperty>^git.build.(time|version)$</includeOnlyProperty>
						<includeOnlyProperty>^git.commit.id.(abbrev|full)$</includeOnlyProperty>
					</includeOnlyProperties>
					<commitIdGenerationMode>full</commitIdGenerationMode>
				</configuration>
			</plugin>
```

- Is there a (public) project where this issue can be reproduced? If so please provide a link.
- Include any stack-traces or any error messages

### Expected behavior
io.github.git-commit-id:git-commit-id-maven-plugin:jar:4.0.0 be available in Maven Central

### Additional context
For reproducibility please provide the following:

- the plugin version is being used (if not included in the configuration)
- the Java-Version is being used (output of ``java -version`` and also include details about oracle-jdk VS open-jdk)
- the Maven-Version is being used (output of ``mvn --version``)
- on what Operating System you experience the bug (on Linux run ``lsb_release -a`` or ``cat /etc/*release*``)
- in what context maven is being executed (e.g. inside Windows Terminal, Powershell, Git Bash, /bin/bash, ...)
- how maven is being executed (e.g. ``mvn clean deploy`` VS ``mvn deploy:deploy``)
- 
C:\Users\fandre\Documents\MXW\Clients\OnePoint\JPMI\jpmi>mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\ASF\apache-maven-3.6.3\bin\..
Java version: 1.8.0_181, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_181\jre
Default locale: fr_FR, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
Feel free to add any other context or screenshots about the bug.

**Comment by TheSnoozer** [comment]
Hi,
thank you for creating this ticket!
Indeed the error message is right. Under https://repo1.maven.org/maven2/io/github/git-commit-id/git-commit-id-maven-plugin/ there is no version **4**.0.0.

For newer version (**5**.x.x or more recent) please use
```xml
<groupId>io.github.git-commit-id</groupId>
<artifactId>git-commit-id-maven-plugin</artifactId>
```
if you want to use an older version (**4**.x.x or older) please use:
```xml
<groupId>pl.project13.maven</groupId>
<artifactId>git-commit-id-plugin</artifactId>
``` 

I guess in your case you'd need to set `git-commit-id-maven-plugin.version` to **5**.0.0 :-)
