### ISSUE TITLE
Generate Yaml format for git information not only properties

### ISSUE THREAD

**Issue by vincenzo-mazzotta** [git-commit-id/git-commit-id-maven-plugin#576]
### Describe your idea
Generate file in yaml format to include in spring profile yaml

### Expected Behavior
Actually I can't find a property that specify output format  when build maven and I can get a new git output file in yaml format.
It's needed to add a new property in XML as <outputFormatFile>value</outputFormatFile> with a default value  and as minimum two formats properties and yml file
### Additional context
It's need to implement yaml format output file but there is a a lot of dependency that you can use to do it.

**Comment by TheSnoozer** [comment]
Indeed yml or yaml is not supported. This seems to be a similar request as https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/568

**Comment by TheSnoozer** [comment]
Closing as duplicate. Thanks for your suggestion. Please follow https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/568 for any updates!
