### ISSUE TITLE
git.properties not written when packaging is pom

### ISSUE THREAD

**Issue by RegalMedia** [git-commit-id/git-commit-id-maven-plugin#578]
### Describe the bug
When using this plugin in a project that uses pom packaging, no git.properties is written.  Unsure if this is by design, or my config is incorrect.  Don't see this explicitly mentioned in the guides.

Switching the packaging to 'jar' works, but when 'pom'...nothing.  Tried various combinations of config settings but nothing seems to generate the file.  I see the plugin start during the build, but it does nothing.  Just looking to have this file written to the root of my project for other parts of the build pipeline to consume, even though this artifact is not generating a jar.

### Steps to Reproduce
- Create new pom project
- Configure plugin
- Package
  (See plugin start...but no file is written)

- Please include the **full** configuration of the plugin
```xml
<plugin>
	<groupId>io.github.git-commit-id</groupId>
	<artifactId>git-commit-id-maven-plugin</artifactId>
	<version>5.0.0</version>
	<executions>
		<execution>
			<id>git-commit-id</id>
			<goals>
				<goal>revision</goal>
			</goals>
			<phase>initialize</phase>
		</execution>
	</executions>
	<configuration>
		<offline>true</offline>
		<failOnNoGitDirectory>false</failOnNoGitDirectory>
		<generateGitPropertiesFile>true</generateGitPropertiesFile>
		<generateGitPropertiesFilename>git.properties</generateGitPropertiesFilename>
	</configuration>
</plugin>
```

- Is there a (public) project where this issue can be reproduced? If so please provide a link
N/A

- Include any stack-traces or any error messages
N/A

### Expected behavior
As long as the plugin is configured and bound to a phase correctly, would expect it to generate its properties file regardless of packaging type.

### Additional context
For reproducibility please provide the following:

- the plugin version is being used (if not included in the configuration)
See above config

- the Java-Version is being used (output of ``java -version`` and also include details about oracle-jdk VS open-jdk)
Oracle JDK11 (11.0.13)

- the Maven-Version is being used (output of ``mvn --version``)
3.8.3
- on what Operating System you experience the bug (on Linux run ``lsb_release -a`` or ``cat /etc/*release*``)
Windows 10

- in what context maven is being executed (e.g. inside Windows Terminal, Powershell, Git Bash, /bin/bash, ...)
Windows terminal

- how maven is being executed (e.g. ``mvn clean deploy`` VS ``mvn deploy:deploy``)
mvn clean package

**Comment by TheSnoozer** [comment]
The plugin skips pom builds by default. Try adding:
``` <skipPoms>false</skipPoms>``` to the plugin config.

See https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/master/docs/using-the-plugin.md for a more in-depth explanation.

**Comment by RegalMedia** [comment]
Thanks, that works.  Hadn't noticed that property originally.  Got it working with the following.  Closing this--not an issue.  Thanks again.

```
‹skipPoms>false</skipPoms>
‹generateGitPropertiesFile›true‹/generateGitPropertiesFile»
<generateGitPropertiesFilename›git.properties‹/generateGitPropertiesFilename›
```

**Comment by TheSnoozer** [comment]
Cool. Glad you got it working!
