### ISSUE TITLE
can not find such file or dictory in SIT

### ISSUE THREAD

**Issue by Sendigod** [git-commit-id/git-commit-id-maven-plugin#579]
Git.properties can be read normally when I access Swagger locally, but when I deploy the project to SIT environment, I cannot read it.

**Comment by TheSnoozer** [comment]
Could you perhaps explain what an SIT environment is? I have never heard that term before....

I guess by the description: is the git.properties also available in the deployed location?

**Comment by TheSnoozer** [comment]
Closing as can not reproduce. Please provide all the information that are requested when opening a ticket, otherwise I can't help.
