### ISSUE TITLE
Git.properties file is not generated using plugin version 5.0.0

### ISSUE THREAD

**Issue by pasolid** [git-commit-id/git-commit-id-maven-plugin#581]
I tried to replace the older plugin `pl.project13.maven` with newer `io.github.git-commit-id` which is supposed to be for projects of Java11 or higher but `git.properties` file is not generated in build folder.

#### My java properties:
Azule-11, version 11.0.12
Maven 3.8.4
Spring Boot Starter Parent 2.4.10

#### Pom.xml
In the `dependencies` I have set dependency on the newest version by:
```xml
<dependency>
    <groupId>io.github.git-commit-id</groupId>
    <artifactId>git-commit-id-maven-plugin</artifactId>
    <version>5.0.0</version>
</dependency>
```

And in the `build.plugins` area I am using this plugin by:
```xml
<plugin>
    <groupId>io.github.git-commit-id</groupId>
    <artifactId>git-commit-id-maven-plugin</artifactId>
    <version>5.0.0</version>
</plugin>
```
Also I tried to add configuration values, just to be sure plugin is not disabled by default:
```xml
<configuration>
    <useNativeGit>true</useNativeGit>
    <generateGitPropertiesFile>true</generateGitPropertiesFile>
</configuration>
```
But nothing is generated.

If I switch back to older version, then the file is generated.
I also see in the build log, the plugin is executed:
```log
[INFO] --- git-commit-id-plugin:2.2.1:revision (default)
...
[INFO] Writing properties file to ...
```

It is not an issue for me to keep using older version, it's just I thought that if the newer version is specifically for +Java11 already exists then why not.

**Comment by TheSnoozer** [comment]
Mhh not sure what could be going on here, hard to read tea leaves without a project where I could reproduce the issue.
I would recommend to validate that the plugin is executed at all. E.g. as you mentioned above the execution is logged inside. Does this not happen for the 5.X version?
The following works just fine for me:
```
<plugin>
				<groupId>io.github.git-commit-id</groupId>
				<artifactId>git-commit-id-maven-plugin</artifactId>
				<version>5.0.0</version>
				<executions>
					<execution>
						<id>get-the-git-infos</id>
						<goals>
							<goal>revision</goal>
						</goals>
						<phase>initialize</phase>
					</execution>
				</executions>
				<configuration>
					<skipPoms>false</skipPoms>
					<verbose>false</verbose>
					<generateGitPropertiesFile>true</generateGitPropertiesFile>
					<generateGitPropertiesFilename>${project.build.outputDirectory}/${project.artifactId}_git.properties</generateGitPropertiesFilename>
				</configuration>
			</plugin>
```

Another alternative of troubleshooting would be closing this repo and running the [demo profile](https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/master/pom.xml#L369) via `mvn clean install -Dmaven.test.skip=true && mvn clean package -Pdemo` or create a reproducer using the [dummy repo](https://github.com/TheSnoozer/git-commit-id-debugging)

**Comment by pasolid** [comment]
Indeed, what I was missing is this part:
```xml
<executions>
    <execution>
        <goals>
            <goal>revision</goal>
        </goals>
     </execution>
 </executions>
```

I wonder, older version worked fine w/o this part but it won't work in version 5.0.0+

Anyway, thanks, this solved my issue
