### ISSUE TITLE
maven parallel build issue

### ISSUE THREAD

**Issue by 1zg12** [git-commit-id/git-commit-id-maven-plugin#583]
### Describe the bug
It seems like the plugin doesn't work with maven parallel build.

### Steps to Reproduce
- Please include the **full** configuration of the plugin

```xml
            <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <version>4.9.10</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

Command for maven
```
mvn -T 2 verify
```

```
mvn -T 4 package
```

- Include any stack-traces or any error messages
It will stuck at 
```
Replacing ....APP-256cef3.jar with ... APP-${git-commit-id.abbrev}.jar
```
### Expected behavior
- Please provide a description of what you expected to happen.
it should finish the build and test in time

### Additional context
For reproducibility please provide the following:

- the plugin version is being used (if not included in the configuration)
- the Java-Version is being used (output of ``java -version`` and also include details about oracle-jdk VS open-jdk)
 1.8
- the Maven-Version is being used (output of ``mvn --version``)
 3
- on what Operating System you experience the bug (on Linux run ``lsb_release -a`` or ``cat /etc/*release*``)
 CentOs
- in what context maven is being executed (e.g. inside Windows Terminal, Powershell, Git Bash, /bin/bash, ...)
 /bin/bash
- how maven is being executed (e.g. ``mvn clean deploy`` VS ``mvn deploy:deploy``)
 `mvn -T 4 package`

Feel free to add any other context or screenshots about the bug.

**Comment by TheSnoozer** [comment]
https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/master/docs/faq.md#generated-properties-are-not-usable-inside-the-pom--properties-dont-get-exposed-by-the-plugin

**Comment by TheSnoozer** [comment]
Please free to reopen if there are any more issues, since there is no further feedback I'd assume my comment resolved your problem.
