### ISSUE TITLE
the calculation of git.dirty is slow in built-in jgit

### ISSUE THREAD

**Issue by guhanjie** [git-commit-id/git-commit-id-maven-plugin#586]
I found the calculation of git.dirty is so slow in my project(maybe the repo is so huge...)

Here is the log:
[info] HEAD is [ *****]

**... this will elapse 10-30s.....**

[info] Repo is in dirty state [ true ]
[info] git.commit.id.describe tags/******
[info] git.commit.id ******
[info] git.commit.id.abbrev ****

**... this will elapse 10-30s.....**

[info] git.dirty true
....
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 43.254 s
[INFO] Finished at: 2022-04-12T21:37:05+08:00
[INFO] Final Memory: 84M/1945M
[INFO] ------------------------------------------------------------------------

Actually, i need no ${git.dirty}, so how can I disable its calculation?

**Comment by guhanjie** [comment]
I found the problem! Use nativeGit rather than built-in jgit, can resolve it.
It seems the built-in jgit run huge git repo is slow.
use 
```
<configuration>
    <useNativeGit>true</useNativeGit>
</configuration>


Here is the reference from doc:
```
                        Explanation:
                        This plugin ships with custom `jgit` implementation that is being used to obtain all
                        relevant information. If set to to `true` this plugin will use the native `git` binary
                        instead of the custom `jgit` implementation.

                        Although this should usually give your build some performance boost, it may randomly
                        break if you upgrade your git version and it decides to print information in a different
                        format suddenly. As rule of thumb, keep using the default `jgit` implementation (keep
                        this `false`) until you notice performance problems within your build (usually when you
                        have *hundreds* of maven modules).
```
>

**Comment by TheSnoozer** [comment]
Indeed as the doc states the native `git` binary is faster so I'm not sure why this ticket was created. Feel free to propose any desired changes as MR, but I'm going ahead and close this.
