### ISSUE TITLE
get the branch name when in detached HEAD (e.g. when a tag is created)

### ISSUE THREAD

**Issue by arauchberger** [git-commit-id/git-commit-id-maven-plugin#595]
### Describe your idea
i'm triggering my maven-pipeline via GitHub-workflow.
when a simple commit triggers the wf, the property `git.branch` tells me the branch correctly (master, my_experiment, ...)
when a `tag` triggers the wf, we have a `detached head situation` and your plugin (as documented) falls back to the commit-id for the property `git.banch`.

### Expected Behavior
property `git.branch` (or an additional property) should always show the branch name for the checked-out commit.

**Comment by arauchberger** [comment]
just as a hint, what i do in the gh-workfow to find out the branch name:

```
GIT_LOG=$(git log -1 --format='%D' $GITHUB_SHA)
```
this gives you something like:
`HEAD -> master, tag: 1.4.3-SNAPSHOT-RC11, origin/master` 

then i remove everything until 'origin/':
```
BRANCH_NAME=$(echo $GIT_LOG | sed -e 's/.*origin\/\(.*\)/\1/')
```
this gives you the branch name:
`master`

**Comment by TheSnoozer** [comment]
Please reopen if still an issue.
