### ISSUE TITLE
Q: a way to automatically execute git-commit-id-plugin with "Build project" under IDEA?

### ISSUE THREAD

**Issue by TheSnoozer** [git-commit-id/git-commit-id-maven-plugin#602]
See https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/474#issuecomment-1494469882
```
Is there any way that this plugin git-commit-id-plugin is executed automatically when doing ''Build Project" (or Rebuild Project)??
```

**Comment by TheSnoozer** [comment]
Maybe https://plugins.jetbrains.com/docs/intellij/external-builder-api.html?

**Comment by paulvi** [comment]
IDEA and Eclipse for maven project have build defined by pom.xml
(There is opposite problem to exclude some plugin from execution when within IDE)

So you need to configure in your maven pom.xml that a plugin is executed within maven build/default cycle.
That is general question, not related to this project.
Better ask on https://stackoverflow.com/ and do googling yourself.
This plugin also has docs.

**Comment by paulvi** [comment]
Hey, it looks like I gave general info to the project maintainer. :-|

Again, I don't think there should be done anything for maven project in IDEA



Remember that IDE usually executes project playing with classpath, there is no .jar
So maven 'package' may not be executed, but 'compile' may be.

What did @wh81752 mean? Why there is need for this?

**Comment by TheSnoozer** [comment]
Won't fix.
