### ISSUE TITLE
If there is a way to compile without reporting an error when the current project does not have a .git directory.

### ISSUE THREAD

**Issue by Zouxxyy** [git-commit-id/git-commit-id-maven-plugin#647]
### Describe the question / problem (required)

A useful tool! I would like to ask if there is a way to compile without reporting an error when the current project does not have a .git directory.

For example, when downloading a simple zip project(no .git), we don't want errors during compilation.

**Comment by TheSnoozer** [comment]
Try:
https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/master/src/main/java/pl/project13/maven/git/GitCommitIdMojo.java#L563
and
https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/master/src/main/java/pl/project13/maven/git/GitCommitIdMojo.java#L583

```xml
<failOnNoGitDirectory>false</failOnNoGitDirectory>
<failOnUnableToExtractRepoInfo>false</failOnUnableToExtractRepoInfo>
```
