### ISSUE TITLE
Support fort Maven's generated pom.properties 

### ISSUE THREAD

**Issue by ikolomiets** [git-commit-id/git-commit-id-maven-plugin#658]
### Describe the idea (required)

Our library already benefits from ability to introspect `pom.properties` file that is automatically generated under /META-INF/maven/..../pom.properties - it is easy to load and use due to unique class path. By default it contains project's `groupId`, `artifactId` and `version` properties. Is it possible to configure `git-commit-id` to use this file for git properties?

### Tell us about the expected behaviour (required)

`pom.properties` to contain `git.commit.id` property.

**Comment by TheSnoozer** [comment]
Hello,
thanks for creating your issue.
This is already supported by maven.

You can either use resource-filtering or create a shaded-jar.

For resource-filtering the trick is to place a pom.properties into `src/main/resources/META-INF/maven/${project.groupId}/${project.artifactId}/pom.properties` the content of the pom.properties is the unfiltered content:
```
#Generated by Git-Commit-Id-Plugin
#${git.build.time}
artifactId=${project.artifactId}
groupId=${project.groupId}
version=${project.version}
git.commit.id=${git.commit.id}
git.branch=${git.branch}
```
By adding the additional filtering the properties are resolved accordingly:
```
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
			</resource>
		</resources>
```

May need to enable `<injectAllReactorProjects>true</injectAllReactorProjects>` as plugin configuration.

The alternative is to use a shaded-jar


See links:
https://maven.apache.org/shared/maven-archiver/
https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html
https://igorski.co/how-to-get-the-pom-properties-at-runtime/
