### ISSUE TITLE
git describe with lightweight tags

### ISSUE THREAD

**Issue by pietermartin** [git-commit-id/git-commit-id-maven-plugin#703]
### Describe the question / problem (required)

`But if you want lightweight tags to be included in the search, enable this option.`

`git describe --tags`  shows my lightweight tags but I can not work out where to enable this option so that the plugin will find my tags?

**Comment by TheSnoozer** [comment]
https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/77f800f2272bc01b8574ea3384fd6501f3700802/src/main/java/pl/project13/maven/git/GitCommitIdMojo.java#L303:
```xml
<gitDescribe>
    <tags>true</tags>
</gitDescribe>
```
See also https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/77f800f2272bc01b8574ea3384fd6501f3700802/pom.xml#L406
