### ISSUE TITLE
Remove FindBugs dependency

### ISSUE THREAD

**Issue by cowwoc** [git-commit-id/git-commit-id-maven-plugin#746]
### Describe the idea (required)

Please remove the dependency on com.google.code.findbugs:jsr305:jar:3.0.2 as it causes a compiler warning:

```
[WARNING] Cannot find annotation method 'value()' in type 'edu.umd.cs.findbugs.annotations.SuppressFBWarnings
```

For those of us using `-Werror`, this breaks the build.

### Tell us about the expected behaviour (required)

No compiler-time warning

**Comment by cowwoc** [comment]
Nevermind. This plugin wasn't at fault. Closing this issue.

**Comment by TheSnoozer** [comment]
Thanks! If there is anything this plugin needs to adjust please free to create a new issue! :-)
